test_blog/blog/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import UserViewSet
from . import views

router = DefaultRouter()
router.register(r'user', UserViewSet)
router.register(r'posts', views.PostViewSet)

urlpatterns = [
    url(r'^$', views.IndexListView.as_view(), name='posts_list'),
    url(r'^detail/(?P<pk>\d+)/$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^create/comment/(?P<pk>\d+)/$', views.CommentCreateView.as_view(), name='comment_create'),
    url(r'^update/comment/(?P<pk>\d+)/(?P<post_id>\d+)$', views.CommentUpdateView.as_view(), name='comment_update'),
    url(r'^create/$', views.PostCreateView.as_view(), name='post_create'),
    url(r'^update/(?P<pk>\d+)/$', views.PostUpdateView.as_view(), name='post_update'),
    url(r'^delete/(?P<pk>\d+)/$', views.PostDeleteView.as_view(), name='post_delete'),
]

urlpatterns += router.urls

test_blog/blog/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _


class Post(models.Model):
    text = models.TextField(_('Текст поста'))
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name=_('Автор'), on_delete=models.CASCADE
    )
    title = models.CharField(_('Заголовок'), max_length=255)
    created_datetime = models.DateTimeField(_('Дата и время создания'), auto_now_add=True)
    edited_datetime = models.DateTimeField(_('Дата и время редактирования'), auto_now=True)
    ordering = models.PositiveIntegerField(_('Номер поста'), null=True, blank=True)
    is_published = models.BooleanField(_('Пост опубликован?'), default=False)

    def __str__(self):
        return '{0} - {1}'.format(self.user.email, self.title)

    class Meta:
        verbose_name = _('Объявление')
        verbose_name_plural = _('Объявления')


class Comment(models.Model):
    text = models.TextField(_('Текст поста'))
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('Автор'),
                             on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE, verbose_name=_('Объявление'))
    created_datetime = models.DateTimeField(_('Дата и время создания'), auto_now_add=True)
    edited_datetime = models.DateTimeField(_('Дата и время редактирования'), auto_now=True)

    def __str__(self):
        return '{0} - {1}'.format(self.user.email, self.post.id)

    class Meta:
        verbose_name = _('Комментарий')
        verbose_name_plural = _('Комментарии')

test_blog/templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Наш супер дупер блог</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet"
          type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
          rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="{% url 'posts_list' %}">Блог</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive"
                aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                {% block menu %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'posts_list' %}">{% trans 'Главная' %}</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'post_create' %}">Создать пост</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
                        </li>
                        <li class="nav-item">
                            <a class="navbar-brand" href="{% url 'update_user' user.id %}">Привет {{ user.get_full_name }}!</a>
                        </li>
                    {% endif %}
                    {% if user.is_anonymous %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Зайти на чай</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'registration' %}">Регистрация</a>
                        </li>
                    {% endif %}
                {% endblock %}
            </ul>
        </div>
    </div>
</nav>

<!-- Page Header -->
<header class="masthead" style="background-image: url('{% static 'img/home-bg.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1>Наш первый блог</h1>
                    <span class="subheading">Добро пожаловать!</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {% block main %}
            {% endblock %}
        </div>
    </div>
</div>

<hr>

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">{% trans 'Copyright &copy; Your Website 2018' %}</p>
            </div>
        </div>
    </div>
</footer>

{% block extra_js %}
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Custom scripts for this template -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>
{% endblock %}

</body>

</html>

test_blog/templates/create_comment_form.html
{% load i18n %}

<form method="post" action="{{ comment_url }}">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <button  class="btn btn-success" type="submit">{% trans 'Отправить комментарий' %}</button>
</form>

test_blog/templates/create_form.html
{% extends 'base.html' %}
{% load i18n %}

{% block main %}
    <form method="post" id="create_form" action="{% url 'post_create' %}">
        <p id="two_input">
            <label for="{{ form.title.id_for_label }}">
                {% trans 'Заголовок:' %}
            </label>
            {{ form.title }}
            <p class="btn-danger">{{ form.title.errors }}</p>
        </p>
        <p id="first_input">
            <label for="{{ form.text.id_for_label }}">
                {% trans 'Текст объявления:' %}
            </label>
            {{ form.text }}
            <p class="btn-danger">{{ form.text.errors }}</p>
        </p>
        <p id="two_input">
            {{ form.captcha }}
            <p class="btn-danger">{{ form.captcha.errors }}</p>
        </p>
        {% csrf_token %}
        <button type="button" class="btn btn-success" id="send_form">{% trans 'Создать' %}</button>
    </form>
{% endblock %}

{% block extra_js %}
    {{ block.super }}
    <script>
    $('body').on('click', '#send_form', function() {
      var form = $('#create_form');
       $.post(form.attr('action'), form.serialize(), function(self) {
         if (self.status == 'ok')
            window.location.replace('/');
         else{
           form.replaceWith(self.html)
         }
       })
    } )
    </script>
{% endblock %}

test_blog/templates/create_form_ajax.html
{% load i18n %}

<form method="post" id="create_form" action="{% url 'post_create' %}">
    <p id="two_input">
        <label for="{{ form.title.id_for_label }}">
            {% trans 'Заголовок:' %}
        </label>
        {{ form.title }}
    <p class="btn-danger">{{ form.title.errors }}</p>
    </p>
    <p id="first_input">
        <label for="{{ form.text.id_for_label }}">
            {% trans 'Текст объявления:' %}
        </label>
        {{ form.text }}
    <p class="btn-danger">{{ form.text.errors }}</p>
    </p>
    <p id="two_input">
        {{ form.captcha }}
    <p class="btn-danger">{{ form.captcha.errors }}</p>
    </p>
    {% csrf_token %}
    <button type="button" class="btn btn-success" id="send_form">{% trans 'Создать' %}</button>
</form>

test_blog/templates/delete_form.html
{% extends 'base.html' %}

{% block main %}
<h3>Вы уверены что хотите удалить объект?</h3>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit">Да, удалить</button>
</form>
{% endblock %}

test_blog/templates/detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block main %}
    {% include 'includes/preview_post.html' %}

    {% include 'create_comment_form.html' %}

    {% for comment in object.comment_set.all %}
        {% include 'includes/comments.html' %}
    {% endfor %}
{% endblock %}

test_blog/templates/index.html
{% extends 'base.html' %}
{% load i18n %}

{% block main %}
    {% for post in posts %}
        {% include 'includes/preview_post.html' %}
    {% empty %}
        <div class="post-preview">
            <h2 class="post-title">{% trans 'Нету объявлений' %}</h2>
        </div>
    {% endfor %}

    {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li>
                    <span><a href="?page={{ page_obj.previous_page_number }}">Previous</a></span>
                </li>
            {% endif %}
            <li class="">
                <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
            </li>
            {% if page_obj.has_next %}
                <li>
                    <span><a href="?page={{ page_obj.next_page_number }}">Next</a></span>
                </li>
            {% endif %}
        </ul>
    {% endif %}
    {% csrf_token %}
{% endblock %}


{% block extra_js %}
    {{ block.super }}
    <script>
      $('body').on('click', '#delete_post', function() {
        var deleteBtn = $(this);
        var form_data = {
          'csrfmiddlewaretoken': $('input[name="csrfmiddlewaretoken"]').val(),
        };
        $.post(deleteBtn.data('href'), form_data, function(self) {
            deleteBtn.closest('.remove_element').slideUp(1000);
        });
      });
    </script>
{% endblock %}

test_blog/templates/registration.html
{% extends 'base.html' %}
{% load i18n %}

{% block main %}
    <form method="post" enctype="multipart/form-data">
         {{ form.as_p }}
        {% csrf_token %}
        <button type="submit">{% trans 'Создать' %}</button>
    </form>
{% endblock %}